"""init db

Revision ID: 2141e19d9d6c
Revises: 
Create Date: 2019-04-29 17:38:46.767787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2141e19d9d6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cad_convert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cad_path', sa.String(length=200), nullable=False),
    sa.Column('cad_type', sa.Integer(), nullable=False),
    sa.Column('target_path', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Integer(), nullable=False),
    sa.Column('convert_status', sa.Integer(), nullable=False),
    sa.Column('covert_time', sa.String(length=15), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solve',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solve_path', sa.String(length=200), nullable=False),
    sa.Column('mesh_path', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('solve_app', sa.Integer(), nullable=True),
    sa.Column('solve_config', sa.JSON(), nullable=False),
    sa.Column('launch_script', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solve_chart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('iteration_step', sa.Integer(), nullable=False),
    sa.Column('multi_fields', sa.JSON(), nullable=False),
    sa.Column('calc_time', sa.Float(), nullable=True),
    sa.Column('capture_time', sa.DateTime(), nullable=False),
    sa.Column('output_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'job_id')
    )
    op.create_table('solve_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solve_job_id', sa.Integer(), nullable=False),
    sa.Column('core_num', sa.Integer(), nullable=False),
    sa.Column('slurm_id', sa.Integer(), nullable=False),
    sa.Column('slurm_status', sa.Integer(), nullable=False),
    sa.Column('total_step', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('log_file', sa.String(length=200), nullable=False),
    sa.Column('error_file', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sovle_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('post_results', sa.JSON(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sovle_results')
    op.drop_table('solve_status')
    op.drop_table('solve_chart')
    op.drop_table('solve')
    op.drop_table('cad_convert')
    # ### end Alembic commands ###
