"""add mesh convert table

Revision ID: a558637583ff
Revises: c96aacfee04c
Create Date: 2019-05-28 10:36:55.047509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a558637583ff'
down_revision = 'c96aacfee04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesh_convert',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mesh_id', sa.Integer(), nullable=False),
    sa.Column('convert_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesh_convert')
    # ### end Alembic commands ###
