"""add mesh  table

Revision ID: c96aacfee04c
Revises: 1894200c814f
Create Date: 2019-05-21 09:52:48.648048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96aacfee04c'
down_revision = '1894200c814f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesh',
    sa.Column('mesh_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meshing_path', sa.String(length=200), nullable=False),
    sa.Column('cad_path', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('mesh_app', sa.Integer(), nullable=False),
    sa.Column('mesh_config', sa.JSON(), nullable=False),
    sa.Column('launch_script', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mesh_id')
    )
    op.create_table('mesh_result',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mesh_id', sa.Integer(), nullable=False),
    sa.Column('mesh_results', sa.JSON(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('mesh_status',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mesh_id', sa.Integer(), nullable=False),
    sa.Column('core_num', sa.Integer(), nullable=False),
    sa.Column('slurm_id', sa.Integer(), nullable=False),
    sa.Column('slurm_status', sa.Integer(), nullable=False),
    sa.Column('total_step', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('log_file', sa.String(length=200), nullable=False),
    sa.Column('error_file', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesh_status')
    op.drop_table('mesh_result')
    op.drop_table('mesh')
    # ### end Alembic commands ###
