"""init db

Revision ID: e213944eaa60
Revises: 2141e19d9d6c
Create Date: 2019-04-29 17:42:21.312731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e213944eaa60'
down_revision = '2141e19d9d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
