"""add Convert table

Revision ID: f58a91543535
Revises: 981b44983ada
Create Date: 2019-05-14 17:13:53.520592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58a91543535'
down_revision = '981b44983ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convert',
    sa.Column('convert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_path', sa.String(length=200), nullable=False),
    sa.Column('output_dir', sa.String(length=200), nullable=False),
    sa.Column('convert_type', sa.Integer(), nullable=False),
    sa.Column('convert_status', sa.Integer(), nullable=False),
    sa.Column('convert_infos', sa.JSON, nullable=True),
    sa.Column('begin_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('convert_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
